MaksimApp/MaxsimApp/Models/ErrorViewModel.cs
namespace MaxsimApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MaksimApp/MaxsimApp/Areas/Admin/Controllers/AccountController.cs
using MaksimApp.Core.Models;
using MaxsimApp.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MaxsimApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AccountController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public AccountController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, RoleManager<IdentityRole> roleManager = null)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        //public async Task<IActionResult> CreateAdmin()
        //{
        //    AppUser user = new AppUser()
        //    {
        //        FullName = "Fatime Kerimli",
        //        UserName = "Kerimliif"
        //    };
        //    await _userManager.CreateAsync(user, "Fatimedi@123");
        //    await _userManager.AddToRoleAsync(user, "Admin");
        //    return Ok();
        //}

        //public async Task<IActionResult> CreateRoles()
        //{

        //    await _roleManager.CreateAsync(new IdentityRole()
        //    {
        //        Name="Admin"
        //    });
        //    await _roleManager.CreateAsync(new IdentityRole()
        //    {
        //        Name = "Moderator"
        //    });
        //    await _roleManager.CreateAsync(new IdentityRole()
        //    {
        //        Name = "Member"
        //    });
        //    return Ok();
        //}

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(AdminLoginVm adminLoginVm)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            AppUser user = await _userManager.FindByNameAsync(adminLoginVm.UserName);
            if(user == null)
            {
                ModelState.AddModelError("","Username veya password yanlisdir!!!");
                return View();
            }
            var result = await _signInManager.CheckPasswordSignInAsync(user, adminLoginVm.Password, true);
            if(!result.Succeeded)
            {
                ModelState.AddModelError("", "Username/Email ve ya Password yanlisdir");
                return View();
            }

            return RedirectToAction("Index", "Dashboard");
        }
    }
}

MaksimApp/MaxsimApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace MaxsimApp.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MaksimApp/MaxsimApp/Areas/Admin/Controllers/ServiceController.cs
using MaksimApp.Business.Excepton;
using MaksimApp.Business.Service.Abstracts;
using MaksimApp.Core.Models;
using Microsoft.AspNetCore.Mvc;

namespace MaxsimApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceController : Controller
    {
        private readonly IServiceServices _services;
       
        public ServiceController(IServiceServices services)
        {
            _services = services;
           
        }

        public IActionResult Index()
        {
            var services=_services.GetAllServices();
            return View(services);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Services services)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                _services.AddServices(services);
            }
            catch (FileContentException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            catch(FileSizeException ex)
            {
                ModelState.AddModelError(ex.PropertyName,ex.Message);
                return View();
            }
            catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        { 
            var existservices= _services.GetServices(x=>x.Id==id);
            if(existservices==null)return NotFound();
            _services.RemoveServices(existservices.Id);

            return RedirectToAction("Index");
        }
  //      [HttpPost]
		//public IActionResult DeleteService(int id)
		//{
		//	var existservices = _services.GetServices(x => x.Id == id);
		//	if (existservices == null) return NotFound();
  //          _services.RemoveServices(id);
		//	return RedirectToAction("Index");
		//}
        public IActionResult Update(int id)
        {
			var existservices = _services.GetServices(x => x.Id == id);
			if (existservices == null) return NotFound();
            return View(existservices);
		}
        [HttpPost]
        public IActionResult Update(Services services)
        {
            if(!ModelState.IsValid) return View();
            _services.UpdateServices(services.Id, services);
            return RedirectToAction("Index");
        }
	}
}

MaksimApp/MaxsimApp/Controllers/HomeController.cs
using MaksimApp.Business.Service.Abstracts;
using MaxsimApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MaxsimApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IServiceServices _serviceServices;

		public HomeController(IServiceServices serviceServices)
		{
			_serviceServices = serviceServices;
		}

		public IActionResult Index()
        {
            var services=_serviceServices.GetAllServices(); 
            return View(services);
        }

       
    }
}

MaksimApp/MaxsimApp/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace MaxsimApp.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MaksimApp/MaxsimApp/Areas/Admin/Views/Service/Create.cshtml
@using MaksimApp.Core.Models;
@model Services
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control">
                <span asp-validation-for="PhotoFile" style="color:red"></span>
            </div>
           </div>
           <div class="mb-3">
               <label asp-for="Description" class="form-label">Description</label>
               <textarea class="form-control" asp-for="Description" rows="3"></textarea>
               <span asp-validation-for="Description" style="color:red"></span>
           
           </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

MaksimApp/MaxsimApp/Areas/Admin/Views/Service/Delete.cshtml
@* @using MaksimApp.Core.Models;

@model Services
<div class="container">
    <div class="row">
        <div class="col-12">
            <form asp-action="DeleteService" method="post" class="card" style="width: 18rem;">
                <img src="~/Upload/Service/@Model.ImageUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@Model.Title</h5>
                    <p class="card-text">@Model.Description</p>
                    <input asp-for="@Model.Id" value="@Model.Id" />
                    <a asp-action="index" asp-controller="service" class="btn btn-warning">Go back</a>
                    <button type="submit" class="btn btn-danger">Delete</button>

                </div>
            </form>
        </div>
    </div>
</div> *@

MaksimApp/MaxsimApp/Areas/Admin/Views/Service/Index.cshtml
@using MaksimApp.Core.Models;
@model List<Services>
@{
    int count = 0;
}
<div class="container">
    <h1>

        Services
        <a class="btn btn-primary" asp-action="Create" asp-controller="Service">Create</a>

    </h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                count++;
                <tr>
                    <td>@count</td>
                    <td>@item.Title</td>

                    <td>@item.Description</td>
                    <td>
                        <div style="width:100px">
                            <img width="100%" src="~/Upload/Service/@item.ImageUrl"></img>
                        </div>
                    </td>




                    <td>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Service" asp-route-id=@item.Id>Delete</a>
                        <a class="btn btn-info" asp-action="Update" asp-controller="Service" asp-route-id=@item.Id>Update</a>
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>

MaksimApp/MaxsimApp/Areas/Admin/Views/Service/Update.cshtml
@using MaksimApp.Core.Models;
@model Services
<div class="container">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="mb-3 col-md-4">
                <label asp-for="Title" class="form-label">Title</label>
                <input asp-for="Title" class="form-control">
                <span asp-validation-for="Title" style="color:red"></span>
            </div>
            <div class="mb-3 col-md-4">
                <label asp-for="PhotoFile" class="form-label">PhotoFile</label>
                <input asp-for="PhotoFile" class="form-control">
                <span asp-validation-for="PhotoFile" style="color:red"></span>
            </div>
        </div>
        <div class="mb-3">
            <label asp-for="Description" class="form-label">Description</label>
            <textarea class="form-control" asp-for="Description" rows="3"></textarea>
            <span asp-validation-for="Description" style="color:red"></span>

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

MaksimApp/MaxsimApp/Views/Page/Index.cshtml
<!-- spacer section -->
<section class="spacer green">
	<div class="container">
		<div class="row">
			<div class="span12 aligncenter flyUp">
				<h2 class="pagetitle">Maxim <strong>Components</strong></h2>
			</div>
		</div>
	</div>
</section>
<!-- end spacer section -->
<!-- section: team -->
<section id="maincontent" class="inner">
	<div class="container">
		<div class="row">
			<div class="span6">
				<h4>Tabs</h4>
				<div class="tabbable">
					<ul class="nav nav-tabs">
						<li class="active"><a href="#one" data-toggle="tab"><i class="icon-rocket"></i> One</a></li>
						<li><a href="#two" data-toggle="tab">Two</a></li>
						<li><a href="#three" data-toggle="tab">Three</a></li>
					</ul>
					<div class="tab-content">
						<div class="tab-pane active" id="one">
							<p>
								<strong>Augue iriure</strong> dolorum per ex, ne iisque ornatus veritus duo. Ex nobis integre lucilius sit, pri ea falli ludus appareat. Eum quodsi fuisset id, nostro patrioque qui id. Nominati eloquentiam in mea.
							</p>
							<p>
								No eum sanctus vituperata reformidans, dicant abhorreant ut pro. Duo id enim iisque praesent, amet intellegat per et, solet referrentur eum et.
							</p>
							<p>
								Tale dolor mea ex, te enim assum suscipit cum, vix aliquid omittantur in. Duo eu cibo dolorum menandri, nam sumo dicit admodum ei. Ne mazim commune honestatis cum, mentitum phaedrum sit et.
							</p>
						</div>
						<div class="tab-pane" id="two">
							<p>
								Tale dolor mea ex, te enim assum suscipit cum, vix aliquid omittantur in. Duo eu cibo dolorum menandri, nam sumo dicit admodum ei. Ne mazim commune honestatis cum, mentitum phaedrum sit et.
							</p>
							<p>
								Tale dolor mea ex, te enim assum suscipit cum, vix aliquid omittantur in. Duo eu cibo dolorum menandri, nam sumo dicit admodum ei. Ne mazim commune honestatis cum, mentitum phaedrum sit et.
							</p>
						</div>
						<div class="tab-pane" id="three">
							<p>
								Cu cum commodo regione definiebas. Cum ea eros laboramus, audire deseruisse his at, munere aeterno ut quo. Et ius doming causae philosophia, vitae bonorum intellegat usu cu.
							</p>
							<p>
								Tale dolor mea ex, te enim assum suscipit cum, vix aliquid omittantur in. Duo eu cibo dolorum menandri, nam sumo dicit admodum ei. Ne mazim commune honestatis cum, mentitum phaedrum sit et.
							</p>
						</div>
					</div>
				</div>
			</div>

			<div class="span6">
				<h4>Accordion</h4>
				<!-- start: Accordion -->
				<div class="accordion" id="accordion2">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle active" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
								<i class="icon-minus"></i> Collapsible Group Item #1
							</a>
						</div>
						<div id="collapseOne" class="accordion-body collapse in">
							<div class="accordion-inner">
								Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
								on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
								raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
								<i class="icon-plus"></i> Collapsible Group Item #2
							</a>
						</div>
						<div id="collapseTwo" class="accordion-body collapse">
							<div class="accordion-inner">
								Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
								on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
								raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
								<i class="icon-plus"></i> Collapsible Group Item #3
							</a>
						</div>
						<div id="collapseThree" class="accordion-body collapse">
							<div class="accordion-inner">
								Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird
								on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table,
								raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
							</div>
						</div>
					</div>
				</div>
				<!--end: Accordion -->
			</div>
		</div>

		<div class="row">
			<div class="span6">
				<h4>Alerts</h4>
				<div class="alert">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Warning!</strong> Best check yo self, you're not looking too good.
				</div>
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Oh snap!</strong> Change a few things up and try submitting again.
				</div>
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Well done!</strong> Change a few things up and try submitting again.
				</div>
				<div class="alert alert-info">
					<button type="button" class="close" data-dismiss="alert">&times;</button>
					<strong>Heads up!</strong> Change a few things up and try submitting again.
				</div>
			</div>
			<div class="span6">
				<h4>Progress</h4>
				<div class="progress progress-primary">
					<div class="bar" style="width: 40%;"></div>
				</div>
				<div class="progress progress-striped">
					<div class="bar" style="width: 20%;"></div>
				</div>
				<div class="progress progress-striped active">
					<div class="bar" style="width: 40%;"></div>
				</div>
				<div class="progress progress-success">
					<div class="bar" style="width: 50%;"></div>
				</div>

				<div class="progress progress-info">
					<div class="bar" style="width: 60%;"></div>
				</div>
				<div class="progress progress-warning">
					<div class="bar" style="width: 70%;"></div>
				</div>
				<div class="progress progress-danger">
					<div class="bar" style="width: 80%;"></div>
				</div>

			</div>
		</div>

		<div class="row">
			<div class="span12">
				<h4 class="heading">Button types<span></span></h4>

				<a href="#" class="btn">btn default</a>
				<a href="#" class="btn btn-theme">btn btn-theme</a>
				<a href="#" class="btn btn-primary">btn-primary</a>
				<a href="#" class="btn btn-warning">btn-warning</a>
				<a href="#" class="btn btn-danger">btn-danger</a>
				<a href="#" class="btn btn-info">btn-info</a>
				<a href="#" class="btn btn-success">btn-success</a>
				<a href="#" class="btn btn-inverse">btn-inverse</a>
			</div>
		</div>


		<div class="row">
			<div class="span6">

				<h4 class="heading">Button sizes<span></span></h4>

				<p>There are 4 button sizes: mini, small, normal and large</p>

				<a href="#" class="btn btn-mini btn-primary">mini size</a>
				<a href="#" class="btn btn-small btn-warning">small size</a>
				<a href="#" class="btn btn-danger">normal size</a>
				<a href="#" class="btn btn-large btn-info">Large size</a>

			</div>
			<div class="span6">
				<h4 class="heading">Button edge<span></span></h4>

				<p>There are 3 button edge variations: normal, rounded and flat. Simply adding <code>btn-rounded</code> or <code>btn-flat</code> class and you'll get different button edge</p>

				<a href="#" class="btn btn-primary">normal primary</a>

				<a href="#" class="btn btn-warning btn-rounded">rounded button</a>
				<a href="#" class="btn btn-danger btn-flat">flat button</a>

				<a href="#" class="btn btn-primary btn-large btn-rounded">large rounded</a>
				<a href="#" class="btn btn-warning btn-mini btn-rounded">rounded button</a>

			</div>
		</div>

	</div>
	<!-- end container -->
</section>

MaksimApp/MaxsimApp/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Maxim - Modern One Page Bootstrap Template</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<link href="~/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="~/css/style.css" rel="stylesheet">
	<link href="color/default.css" rel="stylesheet">
	<link rel="shortcut icon" href="img/favicon.ico">
	<!-- =======================================================
	Theme Name: Maxim
	Theme URL: https://bootstrapmade.com/maxim-free-onepage-bootstrap-theme/
	Author: BootstrapMade.com
	Author URL: https://bootstrapmade.com
	======================================================= -->
</head>

<body>
	<!-- navbar -->
	<div class="navbar-wrapper">
		<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<!-- Responsive navbar -->
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
					</a>
					<h1 class="brand"><a href="index.html">Maxim</a></h1>
					<!-- navigation -->
					<nav class="pull-right nav-collapse collapse">
						<ul id="menu-main" class="nav">
							<li><a title="team" asp-controller="Home" asp-action="index">About</a></li>
							<li><a title="services" href="#services">Services</a></li>
							<li><a title="works" href="#works">Works</a></li>
							<li><a title="blog" href="#blog">Blog</a></li>
							<li><a title="contact" href="#contact">Contact</a></li>
							<li><a asp-controller="Page" asp-action="index">Page</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
	<!-- Header area -->
            @RenderBody()
<footer>
	<div class="container">
		<div class="row">
			<div class="span6 offset3">
				<ul class="social-networks">
					<li><a href="#"><i class="icon-circled icon-bgdark icon-instagram icon-2x"></i></a></li>
					<li><a href="#"><i class="icon-circled icon-bgdark icon-twitter icon-2x"></i></a></li>
					<li><a href="#"><i class="icon-circled icon-bgdark icon-dribbble icon-2x"></i></a></li>
					<li><a href="#"><i class="icon-circled icon-bgdark icon-pinterest icon-2x"></i></a></li>
				</ul>
				<p class="copyright">
					&copy; Maxim Theme. All rights reserved.
					<div class="credits">
						<!--
						  All the links in the footer should remain intact.
						  You can delete the links only if you purchased the pro version.
						  Licensing information: https://bootstrapmade.com/license/
						  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Maxim
						-->
						Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
					</div>
				</p>
			</div>
		</div>
	</div>
	<!-- ./container -->
</footer>
<a href="#" class="scrollup"><i class="icon-angle-up icon-square icon-bgdark icon-2x"></i></a>
<script src="~/js/jquery.js"></script>
<script src="~/js/jquery.scrollTo.js"></script>
<script src="~/js/jquery.nav.js"></script>
<script src="~/js/jquery.localScroll.js"></script>
<script src="~/js/bootstrap.js"></script>
<script src="~/js/jquery.prettyPhoto.js"></script>
<script src="~/js/isotope.js"></script>
<script src="~/js/jquery.flexslider.js"></script>
<script src="~/js/inview.js"></script>
<script src="~/js/animate.js"></script>
<script src="~/js/custom.js"></script>
<script src="contactform/contactform.js"></script>

</body>

</html>